[package]
authors = ["Dilshod Tadjibaev (@antimora)"]
edition = "2021"
license = "MIT/Apache-2.0"
name = "burn-common"
readme = "README.md"
repository = "https://github.com/burn-rs/burn-common"
version = "0.1.0"

[features]
default = ["std"]

std = [
  "rand/std",
]

[dependencies]

# ** Please make sure all dependencies support no_std when std is disabled **

cfg-if = {workspace = true}
const-random = {workspace = true}
rand = {workspace = true}
spin = {workspace = true}# using in place of use std::sync::Mutex;          
uuid = {workspace = true}

[dev-dependencies]
dashmap = {workspace = true}
