[package]
authors = ["Dilshod Tadjibaev (@antimora)"]
edition = "2021"
license = "MIT/Apache-2.0"
name = "burn-common"
description = "Burn common crate."
keywords = []
categories = []
readme = "README.md"
repository = "https://github.com/burn-rs/burn/tree/main/burn-common"
version = "0.8.0"

[features]
default = ["std"]

std = [
  "rand/std",
]

[dependencies]

# ** Please make sure all dependencies support no_std when std is disabled **

const-random = {workspace = true}
rand = {workspace = true}
spin = {workspace = true, features = ["mutex", "spin_mutex", "portable_atomic"]}
portable-atomic = {version = "1.3.3", features = ["critical-section"]}
portable-atomic-util = {version = "0.1.3", features = ["alloc"]}



uuid = {workspace = true}

[dev-dependencies]
dashmap = {workspace = true}
