[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "Vision processing operations for burn tensors"
documentation = "https://docs.rs/burn-vision"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "gpu"]
license.workspace = true
name = "burn-vision"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-vision"
version.workspace = true


[features]
default = ["jit-backend"]
export-tests = ["burn-tensor-testgen"]
jit-backend = ["cubecl", "burn-jit"]

# Test features
cpu = ["export-tests"]
cuda = ["jit-backend", "export-tests"]
vulkan = ["burn-wgpu/vulkan", "wgpu"]
wgpu = ["jit-backend", "export-tests"]

[dependencies]
burn-jit = { path = "../burn-jit", version = "0.17.0", optional = true }
burn-tensor = { path = "../burn-tensor", version = "0.17.0" }
burn-tensor-testgen = { path = "../burn-tensor-testgen", version = "0.17.0", optional = true }
cubecl = { workspace = true, optional = true }
derive-new = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
burn-cuda = { path = "../burn-cuda", version = "0.17.0", default-features = false }
burn-ndarray = { path = "../burn-ndarray", version = "0.17.0" }
burn-wgpu = { path = "../burn-wgpu", version = "0.17.0", default-features = false }
