[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "Vision processing operations for burn tensors"
documentation = "https://docs.rs/burn-vision"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "gpu"]
license.workspace = true
name = "burn-vision"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-vision"
version.workspace = true


[features]
export_tests = ["burn-tensor-testgen"]

[dependencies]
burn-tensor = { path = "../burn-tensor" }
cubecl = { workspace = true }
serde = { workspace = true }

burn-tensor-testgen = { path = "../burn-tensor-testgen", version = "0.17.0", optional = true }
