[package]
name = "burn-train"
version = "0.5.0"
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
description = "Training crate for burn"
repository = "https://github.com/burn-rs/burn"
readme = "README.md"
keywords = ["deep-learning", "machine-learning", "tensor", "pytorch", "ndarray"]
categories = ["science"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
burn-core = { version = "0.5.0", path = "../burn-core" }

# Console
indicatif = "0.17.2"
log4rs = "1.2.0"
log = "0.4.17"

# Metrics
nvml-wrapper = "0.8.0"
textplots = "0.8.0"
rgb = "0.8.34"
terminal_size = "0.2.3"

# Utilities
derive-new = "0.5.9"
serde = { version = "1.0.151", features = ["derive"] }
