[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "Training crate for the Burn framework"
edition = "2021"
keywords = ["deep-learning", "machine-learning", "tensor", "pytorch", "ndarray"]
license = "MIT OR Apache-2.0"
name = "burn-train"
readme = "README.md"
repository = "https://github.com/burn-rs/burn/tree/main/burn-train"
version = "0.9.0"

[features]
default = ["metrics", "ui"]
metrics = [
    "nvml-wrapper",
    "sysinfo",
    "systemstat"
]
ui = [
    "indicatif",
    "rgb",
    "terminal_size",
    "textplots",
]

[dependencies]
burn-core = {path = "../burn-core", version = "0.9.0" }

log = {workspace = true}
tracing-subscriber.workspace = true
tracing-appender.workspace = true
tracing-core.workspace = true

# Metrics
nvml-wrapper = { version = "0.9.0", optional = true }
sysinfo = { version = "0.29.8", optional = true }
systemstat = { version = "0.2.3", optional = true }

# Text UI
indicatif = { version = "0.17.5", optional = true }
rgb = { version = "0.8.36", optional = true }
terminal_size = { version = "0.2.6", optional = true }
textplots = { version = "0.8.0", optional = true }

# Utilities
derive-new = {workspace = true}
serde = {workspace = true, features = ["std", "derive"]}

[dev-dependencies]
burn-ndarray = {path = "../burn-ndarray", version = "0.9.0" }
