[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "custom-wgpu-kernel"
publish = false
version = "0.9.0"

[dependencies]
burn = {path = "../../burn", features=["autodiff", "wgpu"]}

# Serialization
log = {workspace = true}
serde = {workspace = true, features = ["std", "derive"]}

# Wgpu internal dependencies
derive-new = { workspace = true }
bytemuck = { workspace = true }
