version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "crates/burn"
      - "crates/burn-*"
      - "crates/burn-import/*-tests"
      - "examples/*"
      - "xtask"
    schedule:
      interval: "weekly"

# Disable automatic pip updates in tests and examples
#  - package-ecosystem: "pip"
#    directories:
#      - "crates/burn-import/onnx-tests"
#      - "examples/raspberry-pi-pico/tensorflow"
#    schedule:
#      interval: "weekly"
