[workspace]
# require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
  "burn",
  "burn-core",
  "burn-train",
  "burn-derive",
  "burn-tensor",
  "burn-tensor-testgen",
  "burn-dataset",
  "burn-tch",
  "burn-ndarray",
  "burn-autodiff",
  "examples/*",
]
