[workspace]
members = [
  "burn",
  "burn-core",
  "burn-train",
  "burn-derive",
  "burn-tensor",
  "burn-tensor-testgen",
  "burn-dataset",
  "burn-tch",
  "burn-ndarray",
  "burn-autodiff",
  "examples/*",
]
