[workspace]
# require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
  "burn",
  "burn-core",
  "burn-train",
  "burn-derive",
  "burn-tensor",
  "burn-tensor-testgen",
  "burn-dataset",
  "burn-tch",
  "burn-ndarray",
  "burn-autodiff",
  "burn-common",
  "burn-no-std-tests",
  "examples/*",
]

[workspace.dependencies]
const-random = "0.1.15"
dashmap = "5.4.0"
dirs = "4.0.0"
fake = "2.5.0"
flate2 = "1.0.25"
half = {version = "1.6.0", features = [
  "num-traits",
]}# needs to be 1.6 to work with tch
hashbrown = "0.13.2"
indicatif = "0.17.2"
lazy_static = "1.4.0"
libm = "0.2.6"
log = "0.4.17"
log4rs = "1.2.0"
spin = {version = "0.9.5", features = ["mutex", "spin_mutex"]}
thiserror = "1.0.38"

#
# The following packages disable the "std" feature for no_std compatibility
#
derive-new = {version = "0.5.9", default-features = false}
ndarray = {version = "0.15.6", default-features = false}
num-traits = {version = "0.2.15", default-features = false, features = ["libm"]}# libm is for no_std
rand = {version = "0.8.5", default-features = false, features = ["std_rng"]}# std_rng is for no_std 
rand_distr = {version = "0.4.3", default-features = false}
serde = {version = "1.0.152", default-features = false, features = ["derive", "alloc"]}# alloc is for no_std, derive is needed
serde_json = {version = "1.0.91", default-features = false}
uuid = {version = "1.3.0", default-features = false}
