[package]
name = "burn"
version = "0.1.0"
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
description = "BURN: Burn Unstoppable Rusty Neurons"
repository = "https://github.com/nathanielsimard/burn"
readme="README.md"
keywords = ["deep-learning", "machine-learning", "tensor", "pytorch", "ndarray"]
categories = ["science"]
license = "MIT"
edition = "2021"

[dependencies]
burn-tensor = { path = "./burn-tensor", version = "0.1.0" }
rand = "0.8"
