[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "Backend extension for collective calculations."
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "collective"]
license.workspace = true
name = "burn-collective"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-collective"
documentation = "https://docs.rs/burn-collective"
version.workspace = true

[lints]
workspace = true

[features]
default = []
doc = []

# Backends for testing
test-ndarray = ["burn-ndarray"]
test-wgpu = ["burn-wgpu", "burn-wgpu/webgpu"]
test-metal = ["burn-wgpu", "burn-wgpu/metal"]
test-vulkan = ["burn-wgpu", "burn-wgpu/vulkan"]
test-cuda = ["burn-cuda"]

[dependencies]
burn-tensor = { path = "../burn-tensor", version = "0.18.0", default-features = true }
burn-common = { path = "../burn-common", version = "0.18.0", default-features = true }

log = { workspace = true }

burn-ndarray = { path = "../burn-ndarray", version = "0.18.0", optional = true }
burn-wgpu = { path = "../burn-wgpu", version = "0.18.0", optional = true }
burn-cuda = { path = "../burn-cuda", version = "0.18.0", optional = true }

# Server and client dependencies
burn-network = { path = "../burn-network", version = "0.18.0", features = ["data-service"]}
tokio = { workspace = true, features = ["rt-multi-thread", "sync", "signal"] }
serde = { workspace = true, features = ["derive"] }
rmp-serde = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
tokio-util = { workspace = true }


[dev-dependencies]
serial_test = { workspace = true }


[package.metadata.docs.rs]
features = ["doc"]
rustdoc-args = ["--cfg", "docsrs"]
