[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "Backend extension for collective calculations."
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "data"]
license.workspace = true
name = "burn-collective"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-collective"
documentation = "https://docs.rs/burn-collective"
version.workspace = true

[lints]
workspace = true

[features]
default = []
doc = []


[dependencies]
burn-tensor = { path = "../burn-tensor", version = "0.18.0", default-features = true }
burn-common = { path = "../burn-common", version = "0.18.0", default-features = true }
burn-ndarray = { path = "../burn-ndarray", version = "0.18.0" }

# Basic dependencies
derive-new = { workspace = true }
log = { workspace = true }

tokio = { version = "1.45", features = ["rt-multi-thread"] }

serial_test = "3.2.0"


[package.metadata.docs.rs]
features = ["doc"]
rustdoc-args = ["--cfg", "docsrs"]
