[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "Backend extension for collective calculations."
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "data"]
license.workspace = true
name = "burn-collective"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-collective"
documentation = "https://docs.rs/burn-collective"
version.workspace = true

[lints]
workspace = true

[features]
default = []
doc = []

# Backends for testing
ndarray = ["burn-ndarray"]
wgpu = ["burn-wgpu", "burn-wgpu/webgpu"]
metal = ["burn-wgpu", "burn-wgpu/metal"]
vulkan = ["burn-wgpu", "burn-wgpu/vulkan"]
cuda = ["burn-cuda"]

[dependencies]
burn-tensor = { path = "../burn-tensor", version = "0.18.0", default-features = true }
burn-common = { path = "../burn-common", version = "0.18.0", default-features = true }

derive-new = { workspace = true }
log = { workspace = true }

burn-ndarray = { path = "../burn-ndarray", version = "0.18.0", optional = true}
burn-wgpu = { path = "../burn-wgpu", version = "0.18.0", optional = true }
burn-cuda = { path = "../burn-cuda", version = "0.18.0", optional = true}

[dev-dependencies]
cfg-if = { workspace = true }
serial_test = { workspace = true }


[package.metadata.docs.rs]
features = ["doc"]
rustdoc-args = ["--cfg", "docsrs"]
