[package]
name = "burn-autodiff"
version = "0.2.3"
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
description = "Autodiff backend for burn"
repository = "https://github.com/burn-rs/burn/tree/main/burn-autodiff"
readme="README.md"
keywords = ["deep-learning", "machine-learning", "data"]
categories = ["science"]
license = "MIT/Apache-2.0"
edition = "2021"

[features]
default = ["export_tests"]
export_tests = ["burn-tensor-testgen"]

[dependencies]
burn-tensor-testgen = { path = "../burn-tensor-testgen", optional = true }
burn-tensor = { path = "../burn-tensor", version = "0.2.3" }
derive-new = "0.5"
nanoid = "0.4"
