[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "Autodiff backend for burn"
edition = "2021"
keywords = ["deep-learning", "machine-learning", "data"]
license = "MIT/Apache-2.0"
name = "burn-autodiff"
readme = "README.md"
repository = "https://github.com/burn-rs/burn/tree/main/burn-autodiff"
version = "0.6.0"

[features]
default = ["export_tests"]
export_tests = ["burn-tensor-testgen"]

[dependencies]
burn-common = {path = "../burn-common"}
burn-tensor = {path = "../burn-tensor"}
burn-tensor-testgen = {path = "../burn-tensor-testgen", optional = true}

derive-new = {workspace = true, features = ["std"]}# Default enables std
spin = {workspace = true}
