[package]
authors = ["Dilshod Tadjibaev (@antimora)"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "mnist-inference-web"
publish = false
version = "0.10.0"

[lib]
crate-type = ["cdylib"]

[features]
default = []

[dependencies]
burn = {path = "../../burn", default-features = false, features = ["ndarray-no-std"]}
serde = {workspace = true}
wasm-bindgen = "0.2.87"
