[package]
authors = ["Dilshod Tadjibaev (@antimora)"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "mnist-inference-web"
publish = false
version = "0.10.0"

[lib]
crate-type = ["cdylib"]

[features]
default = ["ndarray"]

ndarray = ["burn/ndarray-no-std"]
wgpu = ["burn/wgpu"]

[dependencies]
burn = {path = "../../burn", default-features = false}
serde = {workspace = true}
wasm-bindgen = { version = "0.2.87" } 
wasm-bindgen-futures = "0.4"
js-sys = "0.3.64"

[dev-dependencies]
pollster = { workspace = true }
