[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "guide"
publish = false
version = "0.10.0"

[features]
default = ["train"]
train = ["burn/train"]
train-minimal = ["burn/train-minimal"]

[dependencies]
burn = {path = "../../burn", features = ["wgpu"]}

# Serialization
log = {workspace = true}
serde = {workspace = true, features = ["std", "derive"]}
