[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "guide"
publish = false
version = "0.9.0"

[features]
default = ["burn/dataset-sqlite-bundled"]

[dependencies]
burn = {path = "../../burn", features=["autodiff", "wgpu"]}

# Serialization
log = {workspace = true}
serde = {workspace = true, features = ["std", "derive"]}
