[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "CUDA backend for the Burn framework"
documentation = "https://docs.rs/burn-cuda"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "gpu", "cuda"]
license.workspace = true
name = "burn-cuda"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-cuda"
version.workspace = true

[features]
autotune = ["burn-jit/autotune"]
default = ["fusion", "burn-jit/default", "cubecl/default"]
doc = ["burn-jit/doc"]
fusion = ["burn-fusion", "burn-jit/fusion"]
std = ["burn-jit/std", "cubecl/std"]

[dependencies]
burn-fusion = { path = "../burn-fusion", version = "0.16.0", optional = true }
burn-jit = { path = "../burn-jit", version = "0.16.0", default-features = false }
burn-tensor = { path = "../burn-tensor", version = "0.16.0", features = [
  "cubecl-cuda",
] }
cubecl = { workspace = true, features = ["cuda"] }

bytemuck = { workspace = true }
half = { workspace = true }

derive-new = { workspace = true }
log = { workspace = true }


[dev-dependencies]
burn-jit = { path = "../burn-jit", version = "0.16.0", default-features = false, features = [
  "export_tests",
] }
paste = { workspace = true }


[package.metadata.docs.rs]
features = ["doc"]
rustdoc-args = ["--cfg", "docsrs"]
