[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = ["--cfg", "portable_atomic_critical_section"]
runner = "probe-rs run --chip RP2040"
# runner = "elf2uf2-rs -d -s"

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"
