[package]
name = "autodiff"
version = "0.5.0"
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2021"
publish = false

[features]
default = []

[dependencies]
burn = { path = "../../burn" }
burn-autodiff = { path = "../../burn-autodiff" }
burn-tch = { path = "../../burn-tch" }
burn-ndarray = { path = "../../burn-ndarray" }

# Serialization
serde = { workspace = true, features = ["std", "derive"]}
