[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "text-generation"
publish = false
version = "0.11.0"

[features]
default = ["burn/dataset-sqlite-bundled"]
f16 = []

[dependencies]
# Burn
burn = {path = "../../burn", features=["train", "tch"]}

# Tokenizer
tokenizers = {version = "0.15.0", default-features = false, features = [
  "onig",
  "http",
]}

# Utils
derive-new = {workspace = true}
log = {workspace = true}
serde = {workspace = true, features = ["std", "derive"]}
