[book]
authors = [
    "Wouter Doppenberg",
    "Nathaniel Simard",
    "Louis Fortier-Dubois",
    "Dilshod Tadjibaev",
    "Guillaume Lagrange",
    "Joshua Ferguson"
]
language = "en"
multilingual = false
src = "src"
title = "The Burn Developer Book 🔥"
