[package]
name = "burn-tensor"
version = "0.1.0"
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]

description = """
This library provides multiple tensor implementations hidden behind
an easy to use API that supports reverse mode automatic differentiation.
"""
repository = "https://github.com/nathanielsimard/burn/tree/main/burn-tensor"
readme="README.md"
keywords = ["deep-learning", "machine-learning", "tensor", "pytorch", "ndarray"]
categories = ["science"]
license = "MIT"
edition = "2021"

[features]
default = ["full"]
full = ["tch", "ndarray"]
tch = ["dep:tch"]
ndarray = ["dep:ndarray"]

[dependencies]
num-traits = "0.2"
derive-new = "0.5"
rand = "0.8"
half = { version = "1.6", features = ["num-traits"] } # needs to be 1.6 to work with tch

# Backends
tch = { version = "0.8", optional = true }
lazy_static = "1.4"
ndarray = { version = "0.15", optional = true }

# Autodiff
nanoid = "0.4"

# Serialization
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
