[package]
name = "burn-tensor"
version = "0.1.0"
edition = "2021"

[features]
default = ["tch"]
full = ["arrayfire", "tch"]
arrayfire = ["dep:arrayfire"]
tch = ["dep:tch"]

[dependencies]
derive-new = "0.5"
rand = "0.8"

# Backends
arrayfire = { version = "3.8", optional = true }
tch = { version = "0.8", optional = true }
half = "1.6" # needs to be 1.6 to work with tch

# Autodiff
nanoid = "0.4"

[dev-dependencies]
