[package]
authors = ["Dilshod Tadjibaev (@antimora)"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "onnx-inference"
publish = false
version = "0.10.0"

[features]
default = ["burn/dataset-sqlite-bundled"]

[dependencies]
burn = {path = "../../burn", features=["ndarray"]}
serde = {workspace = true}

[build-dependencies]
burn-import = {path = "../../burn-import"}
