[package]
name = "burn-collective-multinode-tests"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[dependencies]
burn = { path = "../../burn", features = ["ndarray"] }
burn-common = { path = "../../burn-common" }
burn-communication = { path = "../../burn-communication" }
burn-collective = { path = ".." }
tokio = { workspace = true, features = ["rt-multi-thread", "process"] }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
