[package]
name = "burn-collective-multinode-tests"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "global"
path = "src/bin/global.rs"

[[bin]]
name = "node"
path = "src/bin/node.rs"

[dependencies]
burn = { path = "../../burn", features = ["ndarray"] }
burn-common = { path = "../../burn-common" }
burn-communication = { path = "../../burn-communication" }
burn-collective = { path = "..", features = ["orchestrator"]}
tokio = { workspace = true, features = ["rt-multi-thread", "process"] }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
