[package]
name = "burn"
version = "0.4.0"
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
description = "BURN: Burn Unstoppable Rusty Neurons"
repository = "https://github.com/burn-rs/burn"
readme = "README.md"
keywords = ["deep-learning", "machine-learning", "tensor", "pytorch", "ndarray"]
categories = ["science"]
license = "MIT/Apache-2.0"
edition = "2021"

[features]
default = []
experimental-named-tensor = ["burn-core/experimental-named-tensor"]

[dependencies]
burn-core = { version = "0.4.0", path = "../burn-core" }
