[package]
authors = [
  "Dilshod Tadjibaev (@antimora)",
]
edition = "2021"
license = "MIT/Apache-2.0"
name = "burn-import"
readme = "README.md"
repository = "https://github.com/burn-rs/burn/tree/main/burn-import"

version = "0.6.0"

[features]
default = ["onnx"]
onnx = []

[dependencies]
burn = {path = "../burn", version = "0.6.0"}
burn-ndarray = {path = "../burn-ndarray", version = "0.6.0"}

half = {workspace = true}
proc-macro2 = {workspace = true}
protobuf = {version = "3.2", features = ["with-bytes"]}
quote = {workspace = true}
rust-format = {version = "0.3", features = ["token_stream", "post_process"]}
serde = {workspace = true}
strum = {workspace = true}
strum_macros = {workspace = true}
syn = {workspace = true, features = ["parsing"]}
topological-sort = {version = "0.2.2"}

[build-dependencies]
protobuf-codegen = {version = "3.2"}

[dev-dependencies]
rstest = "0.17.0"
