[package]
name = "model"
version = "0.6.1"
edition.workspace = true

[dependencies]
burn = { path = "../../../crates/burn" }
burn-import = { path = "../../../crates/burn-import", features = [
    "pytorch",
], default-features = false }

