[package]
name = "burn-ndarray"
version = "0.2.3"
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]

description = "NdArray backend for burn"
repository = "https://github.com/burn-rs/burn/tree/main/burn-ndarray"
readme="README.md"
keywords = ["deep-learning", "machine-learning", "data"]
categories = ["science"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
burn-tensor = { path = "../burn-tensor", version = "0.2.3", default-features = false }

ndarray = "0.15"
libm = "0.2"
derive-new = "0.5"
rand = "0.8"
num-traits = "0.2"

[dev-dependencies]
burn-tensor = { path = "../burn-tensor", version = "0.2.3", default-features = false, features = ["export_tests"] }
