name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish-burn-derive:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    with:
      crate: burn-derive
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-burn-dataset:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    with:
      crate: burn-dataset
    needs:
      - publish-burn-common
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-burn-common:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    with:
      crate: burn-common
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-burn-tensor-testgen:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    with:
      crate: burn-tensor-testgen
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-burn-tensor:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    needs:
      - publish-burn-tensor-testgen
      - publish-burn-common
    with:
      crate: burn-tensor
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-burn-fusion:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    needs:
      - publish-burn-tensor
      - publish-burn-common
    with:
      crate: burn-fusion
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-burn-jit:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    needs:
      - publish-burn-common
      - publish-burn-fusion
      - publish-burn-tensor
      - publish-burn-ndarray
    with:
      crate: burn-jit
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-burn-autodiff:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    needs:
      - publish-burn-tensor
      - publish-burn-tensor-testgen
      - publish-burn-common
    with:
      crate: burn-autodiff
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-burn-tch:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    needs:
      - publish-burn-tensor
      - publish-burn-autodiff
    with:
      crate: burn-tch
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-burn-ndarray:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    needs:
      - publish-burn-tensor
      - publish-burn-autodiff
      - publish-burn-common
    with:
      crate: burn-ndarray
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-burn-wgpu:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    needs:
      - publish-burn-tensor
      - publish-burn-autodiff
      - publish-burn-ndarray
      - publish-burn-common
      - publish-burn-jit
    with:
      crate: burn-wgpu
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-burn-cuda:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    needs:
      - publish-burn-tensor
      - publish-burn-autodiff
      - publish-burn-ndarray
      - publish-burn-common
      - publish-burn-jit
    with:
      crate: burn-cuda
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-burn-candle:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    needs:
      - publish-burn-tensor
      - publish-burn-autodiff
      - publish-burn-tch
    with:
      crate: burn-candle
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-burn-core:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    needs:
      - publish-burn-dataset
      - publish-burn-common
      - publish-burn-derive
      - publish-burn-tensor
      - publish-burn-autodiff
      - publish-burn-wgpu
      - publish-burn-tch
      - publish-burn-ndarray
      - publish-burn-candle
    with:
      crate: burn-core
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-burn-train:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    needs:
      - publish-burn-core
    with:
      crate: burn-train
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-burn:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    needs:
      - publish-burn-core
      - publish-burn-train
    with:
      crate: burn
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-burn-import:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    needs:
      - publish-burn
    with:
      crate: burn-import
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-onnx-ir:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v1
    with:
      crate: onnx-ir
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
