name: test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, 1.71.0]
        test: ['std', 'no-std', 'examples']
        include:
          - cache: stable
            rust: stable
          - cache: 1-71-0
            rust: 1.71.0
        exclude:
          # only need to check this once
          - rust: 1.71.0
            test: 'examples'

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: install rust
        uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt, clippy
          toolchain: ${{ matrix.rust }}

      - name: caching
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-${{ matrix.cache }}-${{ matrix.test}}-${{ hashFiles('**/Cargo.toml') }}
          prefix-key: "v5-rust"

      - name: free disk space
        run: |
          df -h
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          df -h
          cargo clean --package burn-tch

      - name: install llvmpipe and lavapipe
        run: |
          sudo apt-get update -y -qq
          sudo add-apt-repository ppa:kisak/kisak-mesa -y
          sudo apt-get update
          sudo apt install -y libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers

      - name: Run cargo clippy for stable version
        if: matrix.rust == 'stable' && matrix.test == 'std'
        uses: giraffate/clippy-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Run clippy for each workspace, targets, and featrues, considering
          # warnings as errors
          clippy_flags: --workspace --all-targets --all-features -- -D warnings
          reporter: github-pr-check

      - name: run checks & tests
        run: CI_RUN=1 cargo xtask run-checks ${{ matrix.test }}

  check-typos:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run spelling checks using typos
        run: cargo xtask run-checks typos
