name: test

on:
  push:
    tags:      
      - '*'

jobs:
  publish:
    name: test burn tensor
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install rust nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: check format
        run: |
          cd burn-tensor
          cargo fmt --check --all

      - name: check doc
        run: |
          cd burn-tensor
          cargo test --doc

      - name: check tests
        run: |
          cd burn-tensor
          cargo test --tests

      - name: check clippy backend
        run: |
          cargo clippy -p burn-tensor -- -D warnings
