name: test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, 1.71.0]
        test: ['std', 'no-std']
        include:
          - rust: stable
            rustflags: -Cinstrument-coverage
            rustcomponents: ', llvm-tools-preview'
    steps:
      - name: free disk space
        run: |
          df -h
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          df -h

      - name: checkout
        uses: actions/checkout@v4

      - name: install rust
        uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt, clippy ${{ matrix.rustcomponents }}
          toolchain: ${{ matrix.rust }}

      - name: caching
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
          prefix-key: "v4-rust"

      - name: install llvmpipe and lavapipe
        run: |
          sudo apt-get update -y -qq
          sudo add-apt-repository ppa:kisak/kisak-mesa -y
          sudo apt-get update
          sudo apt install -y libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers

      - name: run checks & tests
        run: RUST_MATRIX=${{ matrix.rust }} cargo xtask run-checks ${{ matrix.test }}
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}
          CARGO_INCREMENTAL: 0
          LLVM_PROFILE_FILE: coverage-%p-%s.profraw

      - name: Install grcov
        if: matrix.rust = 'stable'
        env:
          GRCOV_LINK: https://github.com/mozilla/grcov/releases/download
          GRCOV_VERSION: v0.8.18
        run: |
          curl -L "$GRCOV_LINK/$GRCOV_VERSION/grcov-x86_64-unknown-linux-musl.tar.bz2" |
          tar xj -C $HOME/.cargo/bin

      - name: Run grcov
        if: matrix.rust = 'stable'
        run: grcov . --binary-path target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore 'target/**' --ignore '../**' --ignore '/*' -o lcov.info

      - name: Codecov upload
        if: matrix.rust = 'stable'
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info

  check-typos:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run spelling checks using typos
        run: cargo xtask run-checks typos
