name: test

on:
  push:
    branches:
      - main
      - ci/faster
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  test-burn:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: run checks & tests
          run: ./run-checks.sh
