name: test

on: [push]

jobs:
  publish:
    name: test burn ndarray
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install rust nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: check format
        run: |
          cd burn-ndarray
          cargo fmt --check --all

      - name: check doc
        run: |
          cd burn-ndarray
          cargo test --doc

      - name: check tests
        run: |
          cd burn-ndarray
          cargo test --tests

      - name: check clippy
        run: |
          cargo clippy -p burn-ndarray -- -D warnings
