name: Typos
on: pull_request

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Check spelling
        uses: crate-ci/typos@cad89d4596e2bfb544f3143649ce6eda20de2141