[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "WGPU backend for the Burn framework"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "gpu", "wgpu", "webgpu"]
license.workspace = true
name = "burn-wgpu-new"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/burn-wgpu-new"
version.workspace = true

[features]
default = ["fusion", "burn-wgpu/default"]
fusion = ["burn-fusion", "burn-wgpu/fusion"]

[dependencies]
burn-wgpu = { path = "../burn-wgpu", version = "0.13.0", default-features = false }
burn-compute = { path = "../burn-compute", version = "0.13.0" }
burn-tensor = { path = "../burn-tensor", version = "0.13.0" }
burn-common = { path = "../burn-common", version = "0.13.0" }
burn-fusion = { path = "../burn-fusion", version = "0.13.0", optional = true }

bytemuck = { workspace = true }
wgpu = { workspace = true, features = ["fragile-send-sync-non-atomic-wasm"] }
pollster = { workspace = true }

log = { workspace = true }
futures-intrusive = { workspace = true }
derive-new = { workspace = true }
hashbrown = { workspace = true }

[dev-dependencies]
burn-ndarray = { path = "../burn-ndarray", version = "0.13.0" }
burn-autodiff = { path = "../burn-autodiff", version = "0.13.0", default-features = false, features = [
  "export_tests",
] }
burn-tensor = { path = "../burn-tensor", version = "0.13.0", default-features = false, features = [
  "export_tests",
] }
burn-wgpu = { path = "../burn-wgpu", version = "0.13.0", default-features = false, features = [
  "export_tests",
] }
